id: I6EAA942A
ocr_import_info:
  timestamp: '2023-06-23T16:52:23.968929+00:00'
  batch_id: batch-bb7f
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: PechaJobs
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-06-23 16:56:58.366963+00:00
last_modified: 2023-06-23 16:56:58.366971+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W1NLM1999
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1NLM1999
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ལུགས་ཀྱི་བསྟན་བཅོས་སྐྱེ་བོ་གསོ་བའི་ཐིགས་པ་སོགས།
  languages:
  - bo
  author: སློབ་དཔོན་ཀླུ་སྒྲུབ།
statistics:
  ocr_word_mean_confidence_index: 0.9528843976423234
  ocr_word_median_confidence_index: 0.9981790500000001
bases:
  I1NLM1999_001:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1NLM1999_001
      total_pages: 270
      volume_number: 1
      volume_pages_bdrc_intro: 0
    order: 1
    base_file: I1NLM1999_001.txt
    statistics:
      ocr_word_median_confidence_index: 0.9981790500000001
      ocr_word_mean_confidence_index: 0.9528843976423234
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
